version: "3.8"
services:
  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres
    ports:
      - "8080:8080"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
